/* MAKMAL KOMPUTER */
(function(){
  const MK_KEY='mk_data_full_v1',DEBOUNCE_DELAY=1500,SERVER_URL='https://yourdomain.com/api/save_mk';
  let fadeTimer=null;
  function mk_loadFromStorage(key){const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;}
  function mk_saveToStorage(key,data){localStorage.setItem(key,JSON.stringify(data));markSaved();}
  let mkData=mk_loadFromStorage(MK_KEY)||{status:'Berfungsi',sbb:'',building:'3A (21/21 Komputer Peribadi)',location:'Dalam bangunan sekolah',ganti:'Tiada',lupus:'Tiada',ganti_tarikh:'',lupus_tarikh:'',devices:[]};
  const statusBox=document.getElementById("mk_save_status");
  const mkStatus=document.getElementById('mk_status');
  const mkSebabWrapper=document.getElementById('mk_sbb');
  mkStatus&&mkStatus.addEventListener('change',()=>{if(mkStatus.value==='Tidak Berfungsi'){mkSebabWrapper.style.display='block';}else{mkSebabWrapper.style.display='none';document.getElementById('mk_sbb').value='';}});
  function showStatus(text,color="bg-slate-700",withSpinner=false){if(!statusBox)return;clearTimeout(fadeTimer);let spinner=withSpinner?'<span class="mk-spinner animate-spin mr-2 inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>':"";statusBox.innerHTML=spinner+text;statusBox.className=`mk-badge ${color}`;statusBox.classList.remove("mk-hidden");if(!withSpinner){fadeTimer=setTimeout(()=>statusBox.classList.add("mk-hidden"),3000);}}
  function markUnsaved(){showStatus("✖ Tidak Disimpan","bg-red-600");}
  function markSaved(){showStatus("✔ Disimpan (Local + Server)","bg-emerald-700");}
  function mk$(id){return document.getElementById(id);}
  function mk_genId(){return'mk_'+Date.now()+Math.random().toString(16).slice(2);}
  function mk_uploadToServer(data){showStatus("Menyimpan ke server...","bg-blue-600",true);fetch(SERVER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>r.json()).then(res=>{markSaved();}).catch(err=>{showStatus("⚠ Gagal simpan server","bg-red-700");console.error("Upload MK ERROR:",err);});}
  function mk_debounce(fn,delay){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),delay);};}
  const mk_autoSave=mk_debounce(()=>{mk_saveToStorage(MK_KEY,mkData);mk_uploadToServer(mkData);},DEBOUNCE_DELAY);
  function mk_flagChange(){markUnsaved();mk_autoSave();}
  function mk_renderRow(row,index){const tr=document.createElement('tr');tr.className='border';tr.dataset.id=row.id;tr.innerHTML=`<td class="p-2 border">${index+1}</td><td class="p-2 border"><select class="jenis w-full p-1 border rounded"><option ${row.jenis==='Komputer Peribadi (PC)'?'selected':''}>Komputer Peribadi (PC)</option><option ${row.jenis==='Pencetak (Printer)'?'selected':''}>Pencetak (Printer)</option><option ${row.jenis==='Projektor'?'selected':''}>Projektor</option></select></td><td class="p-2 border"><input class="jenama w-full p-1 border rounded" value="${row.jenama||''}"></td><td class="p-2 border"><input class="model w-full p-1 border rounded" value="${row.model||''}"></td><td class="p-2 border"><input class="nosiri w-full p-1 border rounded" value="${row.nosiri||''}"></td><td class="p-2 border"><select class="status w-full p-1 border rounded"><option ${row.status==='Berfungsi'?'selected':''}>Berfungsi</option><option ${row.status==='Rosak'?'selected':''}>Rosak</option></select></td><td class="p-2 border text-center"><button class="mk_del bg-red-500 text-white px-2 py-1 rounded">Padam</button></td>`;return tr;}
  function mk_updateStats(){if(mkData.status==='Tidak Berkaitan'){if(mk$('mk_total'))mk$('mk_total').textContent='';if(mk$('mk_ok'))mk$('mk_ok').textContent='';if(mk$('mk_broken'))mk$('mk_broken').textContent='';if(mk$('mk_broken_list'))mk$('mk_broken_list').innerHTML='';return;}const total=mkData.devices.length;const ok=mkData.devices.filter(x=>x.status==='Berfungsi').length;const broken=mkData.devices.filter(x=>x.status==='Rosak').length;if(mk$('mk_total'))mk$('mk_total').textContent=total;if(mk$('mk_ok'))mk$('mk_ok').textContent=ok;if(mk$('mk_broken'))mk$('mk_broken').textContent=broken;if(mk$('mk_broken_list')){mk$('mk_broken_list').innerHTML=broken===0?'':`<div class="p-3 bg-red-50 rounded-md"><div class="text-red-700 font-bold mb-1">Senarai Peranti Rosak</div><ul class="ml-4 text-sm">${mkData.devices.filter(x=>x.status==='Rosak').map(x=>`<li>${x.jenis} — ${x.jenama||'-'} ${x.model?('/ '+x.model):''} (${x.nosiri||'-'})</li>`).join('')}</ul></div>`;}}
  function mk_render(){const tbody=mk$('mk_tbody');if(!tbody)return;tbody.innerHTML='';if(mkData.status!=='Tidak Berkaitan'){mkData.devices.forEach((row,i)=>tbody.appendChild(mk_renderRow(row,i)));}mk_updateStats();markSaved();}
  function mk_applyFields(){if(!mk$('mk_status'))return;mk$('mk_status').value=mkData.status||'Berfungsi';if(mk$('mk_sbb')){mk$('mk_sbb').value=mkData.sbb||'';mk$('mk_sbb').classList.toggle('hidden',mkData.status!=='Rosak');}if(mk$('mk_building'))mk$('mk_building').value=mkData.building||'Tidak Berkaitan';if(mk$('mk_location'))mk$('mk_location').value=mkData.location||'Tidak Berkaitan';if(mk$('mk_ganti'))mk$('mk_ganti').value=mkData.ganti||'Tiada';if(mk$('mk_ganti_tarikh')){mk$('mk_ganti_tarikh').value=mkData.ganti_tarikh||'';mk$('mk_ganti_tarikh').classList.toggle('hidden',mkData.ganti!=='Ya');}if(mk$('mk_lupus'))mk$('mk_lupus').value=mkData.lupus||'Tiada';if(mk$('mk_lupus_tarikh')){mk$('mk_lupus_tarikh').value=mkData.lupus_tarikh||'';mk$('mk_lupus_tarikh').classList.toggle('hidden',mkData.lupus!=='Ya');}}
  if(mk$('mk_status'))mk$('mk_status').addEventListener('change',e=>{mkData.status=e.target.value;if(mkData.status==='Tidak Berkaitan'){mkData.building='Tidak Berkaitan';mkData.location='Tidak Berkaitan';mkData.ganti='Tidak Berkaitan';mkData.lupus='Tidak Berkaitan';mkData.ganti_tarikh='';mkData.lupus_tarikh='';mkData.sbb='';mkData.devices=[];}else{if(mkData.building==='Tidak Berkaitan')mkData.building='3A (21/21 Komputer Peribadi)';if(mkData.location==='Tidak Berkaitan')mkData.location='Dalam bangunan sekolah';if(mkData.ganti==='Tidak Berkaitan')mkData.ganti='Tiada';if(mkData.lupus==='Tidak Berkaitan')mkData.lupus='Tiada';}mk_applyFields();mk_render();mk_flagChange();});
  if(mk$('mk_sbb'))mk$('mk_sbb').addEventListener('input',e=>{mkData.sbb=e.target.value;mk_flagChange();});
  if(mk$('mk_building'))mk$('mk_building').addEventListener('change',e=>{mkData.building=e.target.value;mk_flagChange();});
  if(mk$('mk_location'))mk$('mk_location').addEventListener('change',e=>{mkData.location=e.target.value;mk_flagChange();});
  if(mk$('mk_ganti'))mk$('mk_ganti').addEventListener('change',e=>{mkData.ganti=e.target.value;if(mk$('mk_ganti_tarikh'))mk$('mk_ganti_tarikh').classList.toggle('hidden',mkData.ganti!=='Ya');mk_flagChange();});
  if(mk$('mk_ganti_tarikh'))mk$('mk_ganti_tarikh').addEventListener('input',e=>{mkData.ganti_tarikh=e.target.value;mk_flagChange();});
  if(mk$('mk_lupus'))mk$('mk_lupus').addEventListener('change',e=>{mkData.lupus=e.target.value;if(mk$('mk_lupus_tarikh'))mk$('mk_lupus_tarikh').classList.toggle('hidden',mkData.lupus!=='Ya');mk_flagChange();});
  if(mk$('mk_lupus_tarikh'))mk$('mk_lupus_tarikh').addEventListener('input',e=>{mkData.lupus_tarikh=e.target.value;mk_flagChange();});
  if(mk$('mk_add'))mk$('mk_add').addEventListener('click',()=>{if(mkData.status==='Tidak Berkaitan')return;mkData.devices.push({id:mk_genId(),jenis:'Komputer Peribadi (PC)',jenama:'',model:'',nosiri:'',status:'Berfungsi'});mk_render();mk_flagChange();});
  if(mk$('mk_tbody')){mk$('mk_tbody').addEventListener('input',e=>{const tr=e.target.closest('tr');if(!tr)return;const id=tr.dataset.id;const idx=mkData.devices.findIndex(x=>x.id===id);if(idx===-1) return;['jenis','jenama','model','nosiri','status'].forEach(f=>{const el=tr.querySelector('.'+f);if(el)mkData.devices[idx][f]=el.value;});mk_render();mk_flagChange();});mk$('mk_tbody').addEventListener('click',e=>{if(!e.target.closest('.mk_del'))return;const tr=e.target.closest('tr');const id=tr.dataset.id;mkData.devices=mkData.devices.filter(x=>x.id!==id);mk_render();mk_flagChange();});}
  document.addEventListener('DOMContentLoaded',()=>{mk_applyFields();mk_render();showStatus("Sedia untuk mengisi","bg-slate-600");});
})();