/* PdP */
(function(){
  const PDP_KEY='pdp_data_full_v1',DEBOUNCE_DELAY=1500,SERVER_URL='https://yourdomain.com/api/save_pdp';
  let fadeTimer=null;
  function pdp_loadFromStorage(key){const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;}
  function pdp_saveToStorage(key,data){localStorage.setItem(key,JSON.stringify(data));markSaved();}
  let pdpData=pdp_loadFromStorage(PDP_KEY)||{phases:[{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''}],notes:''};
  const statusBox=document.getElementById("pdp_save_status");
  function showStatus(text,colorClass="bg-slate-700",withSpinner=false){if(!statusBox)return;clearTimeout(fadeTimer);let spinnerHTML=withSpinner?'<span class="pdp-spinner animate-spin mr-2 inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>':"";statusBox.innerHTML=spinnerHTML+text;statusBox.className=`pdp-badge ${colorClass}`;statusBox.classList.remove("pdp-hidden");if(!withSpinner){fadeTimer=setTimeout(()=>statusBox.classList.add("pdp-hidden"),3000);}}
  function markUnsaved(){showStatus("✖ Tidak Disimpan","bg-red-600");}
  function markSaved(){showStatus("✔ Disimpan (Local + Server)","bg-emerald-700");}
  function pdp$(id){return document.getElementById(id);}
  function pdp_debounce(fn,delay){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),delay);};}
  function pdp_uploadToServer(data){showStatus("Menyimpan ke server...","bg-blue-600",true);fetch(SERVER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(r=>{if(!r.ok)throw new Error('Server returned '+r.status);return r.json().catch(()=>({ok:true}));}).then(res=>{markSaved();}).catch(err=>{showStatus("⚠ Gagal simpan server","bg-red-700");console.error("Upload PDP ERROR:",err);});}
  const pdp_autoSave=pdp_debounce(()=>{pdp_saveToStorage(PDP_KEY,pdpData);pdp_uploadToServer(pdpData);},DEBOUNCE_DELAY);
  function pdp_flagChange(){markUnsaved();pdp_autoSave();}
  function pdp_applyFields(){for(let i=0;i<4;i++){const n=i+1;const p=pdpData.phases[i];if(pdp$('pdp_company_'+n))pdp$('pdp_company_'+n).value=p.company||'';if(pdp$('pdp_start_'+n))pdp$('pdp_start_'+n).value=p.start||'';if(pdp$('pdp_end_'+n))pdp$('pdp_end_'+n).value=p.end||'';if(pdp$('pdp_laptop_'+n))pdp$('pdp_laptop_'+n).value=p.laptop!=null?p.laptop:0;if(pdp$('pdp_printer_'+n))pdp$('pdp_printer_'+n).value=p.printer!=null?p.printer:0;if(pdp$('pdp_projector_'+n))pdp$('pdp_projector_'+n).value=p.projector!=null?p.projector:0;if(pdp$('pdp_cart_'+n))pdp$('pdp_cart_'+n).value=p.cart!=null?p.cart:0;if(pdp$('pdp_pm_'+n))pdp$('pdp_pm_'+n).value=p.pm||'';}pdp_updateSummary();}
  function pdp_updateSummary(){const totals=pdpData.phases.reduce((acc,p)=>{acc.laptop+=Number(p.laptop||0);acc.printer+=Number(p.printer||0);acc.projector+=Number(p.projector||0);acc.cart+=Number(p.cart||0);return acc;},{laptop:0,printer:0,projector:0,cart:0});const summary=`L:${totals.laptop} P:${totals.printer} Pr:${totals.projector} C:${totals.cart}`;const sumEl=pdp$('pdp_summary');if(sumEl)sumEl.textContent=summary;}
  function bindAllInputs(){for(let i=0;i<4;i++){const n=i+1;if(pdp$('pdp_company_'+n))pdp$('pdp_company_'+n).addEventListener('input',e=>{pdpData.phases[i].company=e.target.value;pdp_flagChange();pdp_updateSummary();});if(pdp$('pdp_start_'+n))pdp$('pdp_start_'+n).addEventListener('change',e=>{pdpData.phases[i].start=e.target.value;pdp_flagChange();});if(pdp$('pdp_end_'+n))pdp$('pdp_end_'+n).addEventListener('change',e=>{pdpData.phases[i].end=e.target.value;pdp_flagChange();});const numericIds=['laptop','printer','projector','cart'];numericIds.forEach(id=>{const el=pdp$(`pdp_${id}_${n}`);if(!el)return;el.addEventListener('input',e=>{let val=e.target.value;let num=parseInt(val);if(isNaN(num)||num<0)num=0;pdpData.phases[i][id]=num;pdp_flagChange();pdp_updateSummary();});});if(pdp$('pdp_pm_'+n))pdp$('pdp_pm_'+n).addEventListener('change',e=>{pdpData.phases[i].pm=e.target.value;pdp_flagChange();});}}
  function pdp_resetPhase(index){if(index<0||index>3)return;pdpData.phases[index]={company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''};pdp_applyFields();pdp_flagChange();}
  function pdp_resetAll(){pdpData={phases:[{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''},{company:'',start:'',end:'',laptop:0,printer:0,projector:0,cart:0,pm:''}],notes:''};pdp_applyFields();pdp_flagChange();}
  document.addEventListener('DOMContentLoaded',()=>{bindAllInputs();pdp_applyFields();showStatus("Sedia untuk mengisi","bg-slate-600");});
  Object.defineProperty(window,'pdp_resetPhase',{value:pdp_resetPhase,writable:false});Object.defineProperty(window,'pdp_resetAll',{value:pdp_resetAll,writable:false});
})();