/* PUSAT AKSES */
(function(){
  const PA_KEY='pa_data_full_v2',DEBOUNCE_DELAY=1500,SERVER_URL='https://yourdomain.com/api/save_pa';
  let fadeTimer=null;
  let paData=pa_loadFromStorage(PA_KEY)||{status:'Berfungsi',ganti:'Tidak',lupus:'Tidak',ganti_tarikh:'',lupus_tarikh:'',devices:[]};
  const statusBox=document.getElementById("pa_save_status");
  const paStatus=document.getElementById('pa_status');
  const paSebabWrapper=document.getElementById('pa_sbb');
  paStatus&&paStatus.addEventListener('change',()=>{if(paStatus.value==='Tidak Berfungsi'){paSebabWrapper.style.display='block';}else{paSebabWrapper.style.display='none';document.getElementById('pa_sbb').value='';}});
  function showStatus(text,color="bg-slate-700",withSpinner=false){if(!statusBox)return;clearTimeout(fadeTimer);let spinnerHTML=withSpinner?'<span class="pa-spinner animate-spin mr-2 inline-block w-4 h-4 border-2 border-white border-t-transparent rounded-full"></span>':"";statusBox.innerHTML=spinnerHTML+text;statusBox.className=`pa-badge ${color}`;statusBox.classList.remove("pa-hidden");if(!withSpinner){fadeTimer=setTimeout(()=>statusBox.classList.add("pa-hidden"),3000);}}
  function markUnsaved(){showStatus("✖ Tidak Disimpan","bg-red-600");}
  function markSaved(){showStatus("✔ Disimpan (Local + Server)","bg-emerald-700");}
  function pa$(id){return document.getElementById(id);}
  function pa_genId(){return'pa_'+Date.now()+Math.random().toString(16).slice(2);}
  function pa_saveToStorage(key,data){localStorage.setItem(key,JSON.stringify(data));markSaved();}
  function pa_loadFromStorage(key){const raw=localStorage.getItem(key);return raw?JSON.parse(raw):null;}
  function pa_uploadToServer(data){showStatus("Menyimpan ke server...","bg-blue-600",true);fetch(SERVER_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}).then(res=>res.json()).then(resp=>{markSaved();}).catch(err=>{showStatus("⚠ Gagal simpan server","bg-red-700");console.error("Upload PA error:",err);});}
  function pa_debounce(fn,delay){let t;return(...a)=>{clearTimeout(t);t=setTimeout(()=>fn(...a),delay);};}
  const pa_autoSave=pa_debounce(()=>{pa_saveToStorage(PA_KEY,paData);pa_uploadToServer(paData);},DEBOUNCE_DELAY);
  function pa_flagChange(){markUnsaved();pa_autoSave();}
  function pa_renderSelectValue(opts,val){return opts.map(o=>`<option ${o===val?'selected':''}>${o}</option>`).join('');}
  function pa_renderRow(row,index){const tr=document.createElement('tr');tr.className='border';tr.dataset.id=row.id;tr.classList.add(row.status==='Berfungsi'?'status-berfungsi':row.status==='Rosak'?'status-rosak':'');tr.innerHTML=`<td class="p-2 border text-sm">${index+1}</td><td class="p-2 border"><select class="w-full p-1 border rounded jenis">${pa_renderSelectValue(['Komputer Peribadi (PC)','Pencetak (Printer)','Projektor'],row.jenis)}</select></td><td class="p-2 border"><input class="w-full p-1 border rounded jenama" value="${row.jenama||''}"></td><td class="p-2 border"><input class="w-full p-1 border rounded model" value="${row.model||''}"></td><td class="p-2 border"><input class="w-full p-1 border rounded nosiri" value="${row.nosiri||''}"></td><td class="p-2 border"><select class="w-full p-1 border rounded status"><option ${row.status==='Berfungsi'?'selected':''}>Berfungsi</option><option ${row.status==='Rosak'?'selected':''}>Rosak</option></select></td><td class="p-2 border text-center"><button class="pa_del bg-red-500 text-white px-2 py-1 rounded">Padam</button></td>`;return tr;}
  function pa_updatePAStats(){if(paData.status==='Tidak Berkaitan'){['pa_total','pa_ok','pa_broken'].forEach(id=>pa$(id)&&(pa$(id).textContent=''));if(pa$('pa_broken_list'))pa$('pa_broken_list').innerHTML='';return;}const t=paData.devices.length;const ok=paData.devices.filter(x=>x.status==='Berfungsi').length;const b=paData.devices.filter(x=>x.status==='Rosak').length;if(pa$('pa_total'))pa$('pa_total').textContent=t;if(pa$('pa_ok'))pa$('pa_ok').textContent=ok;if(pa$('pa_broken'))pa$('pa_broken').textContent=b;if(pa$('pa_broken_list')){pa$('pa_broken_list').innerHTML=b===0?'':`<div class="p-3 bg-red-50 rounded-md"><div class="text-red-700 font-bold mb-1">Senarai Peranti Rosak</div><ul class="ml-4 text-sm">${paData.devices.filter(x=>x.status==='Rosak').map(x=>`<li>${x.jenis} — ${x.jenama||'-'} ${x.model?'/ '+x.model:''} (${x.nosiri||'-'})</li>`).join('')}</ul></div>`;}}
  function pa_renderPA(){const tbody=pa$('pa_tbody');if(!tbody)return;tbody.innerHTML='';if(paData.status!=='Tidak Berkaitan'){paData.devices.forEach((row,i)=>tbody.appendChild(pa_renderRow(row,i))); }pa_updatePAStats();markSaved();}
  function pa_applyStatusFields(){if(pa$('pa_status'))pa$('pa_status').value=paData.status;if(pa$('pa_ganti'))pa$('pa_ganti').value=paData.ganti;if(pa$('pa_lupus'))pa$('pa_lupus').value=paData.lupus;if(pa$('pa_ganti_tarikh'))pa$('pa_ganti_tarikh').value=paData.ganti_tarikh;if(pa$('pa_lupus_tarikh'))pa$('pa_lupus_tarikh').value=paData.lupus_tarikh;if(pa$('pa_ganti_tarikh'))pa$('pa_ganti_tarikh').classList.toggle('hidden',paData.ganti!=='Ya');if(pa$('pa_lupus_tarikh'))pa$('pa_lupus_tarikh').classList.toggle('hidden',paData.lupus!=='Ya');}
  if(pa$('pa_status'))pa$('pa_status').addEventListener('change',e=>{paData.status=e.target.value;if(paData.status==='Tidak Berkaitan'){paData.ganti='Tidak Berkaitan';paData.lupus='Tidak Berkaitan';paData.ganti_tarikh='';paData.lupus_tarikh='';paData.devices=[];}else{if(paData.ganti==='Tidak Berkaitan')paData.ganti='Tidak';if(paData.lupus==='Tidak Berkaitan')paData.lupus='Tidak';}pa_applyStatusFields();pa_renderPA();pa_flagChange();});
  if(pa$('pa_ganti'))pa$('pa_ganti').addEventListener('change',e=>{paData.ganti=e.target.value;if(pa$('pa_ganti_tarikh'))pa$('pa_ganti_tarikh').classList.toggle('hidden',paData.ganti!=='Ya');pa_flagChange();});
  if(pa$('pa_ganti_tarikh'))pa$('pa_ganti_tarikh').addEventListener('input',e=>{paData.ganti_tarikh=e.target.value;pa_flagChange();});
  if(pa$('pa_lupus'))pa$('pa_lupus').addEventListener('change',e=>{paData.lupus=e.target.value;if(pa$('pa_lupus_tarikh'))pa$('pa_lupus_tarikh').classList.toggle('hidden',paData.lupus!=='Ya');pa_flagChange();});
  if(pa$('pa_lupus_tarikh'))pa$('pa_lupus_tarikh').addEventListener('input',e=>{paData.lupus_tarikh=e.target.value;pa_flagChange();});
  if(pa$('pa_add'))pa$('pa_add').addEventListener('click',()=>{if(paData.status==='Tidak Berkaitan')return;const row={id:pa_genId(),jenis:'Komputer Peribadi (PC)',jenama:'',model:'',nosiri:'',status:'Berfungsi'};paData.devices.push(row);pa_renderPA();pa_flagChange();});
  if(pa$('pa_tbody')){pa$('pa_tbody').addEventListener('input',e=>{const tr=e.target.closest('tr');if(!tr)return;const idx=paData.devices.findIndex(x=>x.id===tr.dataset.id);if(idx===-1)return;['jenis','jenama','model','nosiri','status'].forEach(f=>{const el=tr.querySelector('.'+f);if(el)paData.devices[idx][f]=el.value;});pa_renderPA();pa_flagChange();});pa$('pa_tbody').addEventListener('click',e=>{if(!e.target.closest('.pa_del'))return;const tr=e.target.closest('tr');const id=tr.dataset.id;paData.devices=paData.devices.filter(x=>x.id!==id);pa_renderPA();pa_flagChange();});}
  document.addEventListener('DOMContentLoaded',()=>{pa_applyStatusFields();pa_renderPA();showStatus("Sedia untuk mengisi","bg-slate-600");});
})();